### PR TITLE
Rename erb file

### PR DESCRIPTION
**Pull request by matzew**
for redhat the `erb` file is named `jboss-init.erb`, doing the same for debian.

See also usage here:
https://github.com/andy-dufour/chef-jboss7/blob/master/recipes/default.rb#L63

### CODE REVIEW

**Comment by matzew** [comment]
@andy-dufour any comments on this ?

**Comment by andy-dufour** [comment]
There's more wrong then just the name of the file. The init provider also doesn't work cross platform.

I'm working on a larger commit to fix both issues.

**Comment by matzew** [comment]
@andy-dufour ah, good to know!

**Comment by matzew** [comment]
@andy-dufour sure you won't let this PR go in ?

**Pull request closed without merging**
